name: Give Strava Kudos

on:
  schedule:
    - cron: "30 5-23/6 * * *"
  workflow_dispatch:

env:
  STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
  STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
jobs:
  run-kudos-cron:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: sudo apt-get update && sudo apt-get install -y libdbus-glib-1-2 libnss3 libatk-bridge2.0-0 libgtk-3-0 libasound2 fonts-liberation
      - run: playwright install
      - run: python give_kudos.py
        
